version: '2'
services:
  product:
    image: aigdigital/product-service-ketul:latest
    ports:
     - "9091:9091"
  order:
    image: aigdigital/order-service-ketul:latest
    ports:
     - "9092:9092"
    depends_on:
     - product
